###Create new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "cristian@email.com",
    "password": "passSegura"
}

### find a particular user

GET http://localhost:3000/auth/1


### find all users with given email
GET  http://localhost:3000/auth?email=cristian@email.com

### Delete a particular user

DELETE http://localhost:3000/auth/2

### update a user

PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
    "password": "passMasSegura"
}
